### ISSUE TITLE
Non-windows release?

### ISSUE THREAD

**Issue by eddelbuettel** [thirdwing/RcppMLPACK#9]
Should we alter DESCRIPTION to (for now) focus on Unix as a proxy for systems with 'real-compilers'?

Alternatively, say  Depends: R (>= 3.3.0)   ?

**Comment by thirdwing** [comment]
I will do that a little later. 

Stuck in a bug (https://github.com/dmlc/mxnet/pull/1673).

Sometimes it works well, sometimes it doesn't. This is really annoying.

**Comment by thirdwing** [comment]
Upgrading is not that easy. Let's do a unix-only release first.
